# Generated by Django 3.0.6 on 2020-05-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('matchid', models.IntegerField(primary_key=True, serialize=False)),
                ('coun1', models.CharField(max_length=200)),
                ('coun2', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Players', to='players.Players')),
                ('matchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Matches')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Players')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.User')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField()),
                ('catches', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('matchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Matches')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Players')),
            ],
        ),
    ]
